import request from '@/utils/request'
export const getDepositList = params => request({ url: '/admin/application/deposit', method: 'get', params })
export const getMaterialList = params => request({ url: '/admin/application/material', method: 'get', params })
export const getArticleList = params => request({ url: '/admin/application/article', method: 'get', params })
export const createArticle = data => request({ url: '/admin/application/article', method: 'post', data })
export const updateArticle = (id, data) => request({ url: `/admin/application/article/${id}`, method: 'put', data })
export const deleteArticle = id => request({ url: `/admin/application/article/${id}`, method: 'delete' })
export const getArticleCategories = () => request({ url: '/admin/application/article-categories', method: 'get' })
export const getNoticeList = params => request({ url: '/admin/application/notice', method: 'get', params })
export const createNotice = data => request({ url: '/admin/application/notice', method: 'post', data })
export const updateNotice = (id, data) => request({ url: `/admin/application/notice/${id}`, method: 'put', data })
export const deleteNotice = id => request({ url: `/admin/application/notice/${id}`, method: 'delete' })
export const getKefuSetting = () => request({ url: '/admin/application/kefu', method: 'get' })
export const saveKefuSetting = data => request({ url: '/admin/application/kefu', method: 'post', data })
export const getCollectList = params => request({ url: '/admin/application/collect', method: 'get', params })
