import request from '@/utils/request'
export const getDeliveryTypeList = () => request({ url: '/admin/delivery-type', method: 'get' })
export const createDeliveryType = data => request({ url: '/admin/delivery-type', method: 'post', data })
export const updateDeliveryType = (id, data) => request({ url: `/admin/delivery-type/${id}`, method: 'put', data })
export const deleteDeliveryType = id => request({ url: `/admin/delivery-type/${id}`, method: 'delete' })
export const getOrderSetting = () => request({ url: '/admin/order-setting', method: 'get' })
export const saveOrderSetting = data => request({ url: '/admin/order-setting', method: 'post', data })
export const getPtOpenList = params => request({ url: '/admin/pt-open', method: 'get', params })
export const getShopMenuList = () => request({ url: '/admin/shop-menu', method: 'get' })
export const createShopMenu = data => request({ url: '/admin/shop-menu', method: 'post', data })
export const updateShopMenu = (id, data) => request({ url: `/admin/shop-menu/${id}`, method: 'put', data })
export const deleteShopMenu = id => request({ url: `/admin/shop-menu/${id}`, method: 'delete' })
export const getNoticeSettingList = () => request({ url: '/admin/notice-setting', method: 'get' })
export const updateNoticeSetting = (id, data) => request({ url: `/admin/notice-setting/${id}`, method: 'put', data })
export const getSmsConfig = () => request({ url: '/admin/sms-config', method: 'get' })
export const saveSmsConfig = data => request({ url: '/admin/sms-config', method: 'post', data })
export const getStorageConfig = () => request({ url: '/admin/storage', method: 'get' })
export const saveStorageConfig = data => request({ url: '/admin/storage', method: 'post', data })
export const clearCache = () => request({ url: '/admin/cache/clear', method: 'post' })
export const getTransactionSetting = () => request({ url: '/admin/transaction-setting', method: 'get' })
export const saveTransactionSetting = data => request({ url: '/admin/transaction-setting', method: 'post', data })
export const getUserSetting = () => request({ url: '/admin/user-setting', method: 'get' })
export const saveUserSetting = data => request({ url: '/admin/user-setting', method: 'post', data })
export const getWebSetting = type => request({ url: `/admin/web-setting/${type}`, method: 'get' })
export const saveWebSetting = (type, data) => request({ url: `/admin/web-setting/${type}`, method: 'post', data })
