import request from '@/utils/request'
export const getDictTypeList = () => request({ url: '/admin/system-config/dict-types', method: 'get' })
export const createDictType = data => request({ url: '/admin/system-config/dict-types', method: 'post', data })
export const updateDictType = (id, data) => request({ url: `/admin/system-config/dict-types/${id}`, method: 'put', data })
export const deleteDictType = id => request({ url: `/admin/system-config/dict-types/${id}`, method: 'delete' })
export const getDictDataList = params => request({ url: '/admin/system-config/dict-datas', method: 'get', params })
export const createDictData = data => request({ url: '/admin/system-config/dict-datas', method: 'post', data })
export const updateDictData = (id, data) => request({ url: `/admin/system-config/dict-datas/${id}`, method: 'put', data })
export const deleteDictData = id => request({ url: `/admin/system-config/dict-datas/${id}`, method: 'delete' })
export const getHotSearchList = () => request({ url: '/admin/system-config/hot-searches', method: 'get' })
export const createHotSearch = data => request({ url: '/admin/system-config/hot-searches', method: 'post', data })
export const updateHotSearch = (id, data) => request({ url: `/admin/system-config/hot-searches/${id}`, method: 'put', data })
export const deleteHotSearch = id => request({ url: `/admin/system-config/hot-searches/${id}`, method: 'delete' })
export const getCrontabList = () => request({ url: '/admin/system-config/crontabs', method: 'get' })
export const toggleCrontab = id => request({ url: `/admin/system-config/crontabs/${id}/toggle`, method: 'post' })
export const getAreaList = params => request({ url: '/admin/system-config/areas', method: 'get', params })
export const getExpressTemplateList = () => request({ url: '/admin/system-config/express-templates', method: 'get' })
export const createExpressTemplate = data => request({ url: '/admin/system-config/express-templates', method: 'post', data })
export const updateExpressTemplate = (id, data) => request({ url: `/admin/system-config/express-templates/${id}`, method: 'put', data })
export const deleteExpressTemplate = id => request({ url: `/admin/system-config/express-templates/${id}`, method: 'delete' })
export const getFileList = params => request({ url: '/admin/system-config/files', method: 'get', params })
export const getFileCategoryList = () => request({ url: '/admin/system-config/file-categories', method: 'get' })
