import request from '@/utils/request'
export const getSystemInfo = () => request({ url: '/admin/system-info', method: 'get' })
export const getUpgradeList = () => request({ url: '/admin/upgrade', method: 'get' })
export const getGeneratorTables = () => request({ url: '/admin/generator/tables', method: 'get' })
export const getGeneratorTable = table => request({ url: `/admin/generator/table?table=${table}`, method: 'get' })
export const generateCode = data => request({ url: '/admin/generator/generate', method: 'post', data })
export const exportData = data => request({ url: '/admin/export', method: 'post', data })
export const getGoodsSkuList = params => request({ url: '/admin/goods-sku', method: 'get', params })
export const createGoodsSku = data => request({ url: '/admin/goods-sku', method: 'post', data })
export const updateGoodsSku = (id, data) => request({ url: `/admin/goods-sku/${id}`, method: 'put', data })
export const deleteGoodsSku = id => request({ url: `/admin/goods-sku/${id}`, method: 'delete' })
export const getOrderLogList = params => request({ url: '/admin/order-log', method: 'get', params })
export const getUserAuthList = params => request({ url: '/admin/user-auth', method: 'get', params })
export const auditUserAuth = (id, data) => request({ url: `/admin/user-auth/${id}/audit`, method: 'post', data })
export const getShopAdminList = params => request({ url: '/admin/shop-permission/admins', method: 'get', params })
export const getShopRoleList = params => request({ url: '/admin/shop-permission/roles', method: 'get', params })
export const getShopDeptList = params => request({ url: '/admin/shop-permission/depts', method: 'get', params })
export const getShopJobList = params => request({ url: '/admin/shop-permission/jobs', method: 'get', params })
export const getAdminDeptList = () => request({ url: '/admin/admin-dept', method: 'get' })
